export const authConfig = {
  allowChangeEmail: true,
  allowDeleteUser: true,
  allowAccountLinking: true,
  allowDifferentEmailsOnLink: false,
  requireEmailVerification: true,
  sendVerificationEmailOnSignup: true,
  autoSignInAfterVerification: true,
  verificationTokenExpiresInHours: 24,
  passwordResetTokenExpiresInHours: 1,
  sendPasswordResetConfirmationEmail: true,
  sessionExpiresIn: 60 * 60 * 24 * 7,
  sessionUpdateAge: 60 * 60 * 24,
  sessionFreshAge: 60 * 60 * 24,
  passwordValidation: {
    minLength: 8,
    maxLength: 128,
  },
  enableTwoFactor: true,
  twoFactorIssuer: "Acme",
  enablePasskeys: true,
  enableMagicLink: false,
  magicLinkTokenExpiresInMinutes: 5,
  enableHaveIBeenPwned: true,
} as const;
