export const authConfig = {
  allowChangeEmail: true,
  allowDeleteUser: true,
  allowAccountLinking: true,
  allowDifferentEmailsOnLink: false,
  requireEmailVerification: true,
  sendVerificationEmailOnSignup: true,
  autoSignInAfterVerification: true,
  verificationTokenExpiresInHours: 24,
  passwordResetTokenExpiresInHours: 1,
  sendPasswordResetConfirmationEmail: true,
  sessionExpiresIn: 60 * 60 * 24 * 7,
  sessionUpdateAge: 60 * 60 * 24,
  sessionFreshAge: 60 * 60 * 24,
  enableTwoFactor: true,
  adminPortalTotpRequired: true,
  twoFactorIssuer: "Acme",
  allowBackupCodeRegeneration: true,
  enablePasskeys: true,
  enableMagicLink: false,
  magicLinkOnly: false,
  magicLinkTokenExpiresInMinutes: 5,
  enableSocialAuth: true,
  enableHaveIBeenPwned: true,
  adminPaginationLimit: 10,
  notificationsDropdownLimit: 5,
  notificationsPollingInterval: 30000,
  deleteAccountCountdownSeconds: 10,
  rememberMeEnabled: true,
  confirmPasswordEnabled: true,
  passwordValidation: {
    minLength: 8,
    maxLength: 128,
    regex: undefined as RegExp | undefined,
  },
} as const;

export type AuthConfig = typeof authConfig;
export type PasswordValidation = typeof authConfig.passwordValidation;
